### ISSUE TITLE
Folder containing one SVG throws "Output must be a XML file."

### ISSUE THREAD

**Issue by fedemkr** [Ashung/svg2vectordrawable#23]
If I have a folder with just one SVG like this

📂  MyFolder
  |____ 📄 myFile.svg

and I execute 

```
s2v -f MyFolder -o MyFolder
```

it throws an error saying `Output must be a XML file` so I imagine that when there is only one file it's wrongly executing part of the code of `s2v -i input.svg -o output.xml`

If the folder has two or more files it works with no problems 😄

**Comment by Ashung** [comment]
Bug fixed, update 2.6.1.
