### ISSUE TITLE
Inconsistent output name

### ISSUE THREAD

**Issue by Quentin1010** [Ashung/svg2vectordrawable#38]
Couldn't find an issue for this, so here I am!

Asking for an ouput such as "ic-my-icon.xml" creates a file named "ic_my_icon.xml". Is it a technical limitation or something done on purpose?

**Comment by guliash** [comment]
https://github.com/Ashung/svg2vectordrawable/blob/master/lib/coa.js#L179
The code which transforms '-' to '_'. Do not know the reason why it is needed.

**Comment by Ashung** [comment]
https://stackoverflow.com/questions/5949395/naming-rules-for-android-resources
