### ISSUE TITLE
SVG import causes strange groups

### ISSUE THREAD

**Issue by TobiasReich** [Ashung/svg2vectordrawable#39]
We are using this framework (version 2.6.17) in order to import svgs into Android externally.
However it looks like some layers get strangely distorted in comparison to the imported one from Android Studio.

It appears to happen for mirrowed / rotated layers.

So here is one example:
I added the SVG original graphic as well as a successfull one (import from IDE) and the wrong one (via framework)
[svgImport.zip](https://github.com/Ashung/svg2vectordrawable/files/3652611/svgImport.zip)

One obvious change is the newly appearing group there which rotates everything where the old one did not show any group. The SVG seems to have these rotation but something goes wrong on the import.

**Comment by TobiasReich** [comment]
What it should look like:
<img width="165" alt="Screenshot 2019-09-25 at 15 14 18" src="https://user-images.githubusercontent.com/10375845/65604115-2bddcf00-dfa7-11e9-90c2-50ae433da68f.png">

What it actually looks like:
![Screenshot 2019-09-25 at 15 14 04](https://user-images.githubusercontent.com/10375845/65604116-2bddcf00-dfa7-11e9-9873-a7b2926095d2.png)

**Comment by TobiasReich** [comment]
Our designer created another version without the rotation / flipping. However, it still shows some translation that shouldn't be there - having the svg looking normal.

[svg2.zip](https://github.com/Ashung/svg2vectordrawable/files/3652677/svg2.zip)

Hope this helps finding the issue.

**Comment by Ashung** [comment]
Fixed, use version 2.6.18.

**Comment by TobiasReich** [comment]
Works like a charm. Thanks!
