### ISSUE TITLE
SVG group element not interpreted

### ISSUE THREAD

**Issue by TobiasReich** [Ashung/svg2vectordrawable#40]
So there is another issue I discovered.

There is a svg that has a **group <g>** with a **fill** parameter.  However it looks like this is not transferred to the converted vector drawable.
That leads to "transparent" group / paths.

![Screenshot 2019-09-26 at 11 38 24](https://user-images.githubusercontent.com/10375845/65677582-2d180600-e052-11e9-8292-58472191879e.png)
<img width="147" alt="Screenshot 2019-09-26 at 11 38 20" src="https://user-images.githubusercontent.com/10375845/65677591-3012f680-e052-11e9-939f-4176793d3038.png">

[groupError.zip](https://github.com/Ashung/svg2vectordrawable/files/3657108/groupError.zip)

**Comment by TobiasReich** [comment]
Some more material. Looks like the groups are converted into the vector graphic but not well interpreted. The converter from Android Studio simply creates paths.

[svg2vector.zip](https://github.com/Ashung/svg2vectordrawable/files/3662193/svg2vector.zip)

**Comment by Ashung** [comment]
Fixed, update version 2.6.19.

**Comment by TobiasReich** [comment]
Sorry to bother you but it still looks wrong.
Now it shows up like this. I probably should make a new issue for it...

![Screenshot 2019-09-27 at 15 34 22](https://user-images.githubusercontent.com/10375845/65773313-5c0aa680-e13c-11e9-97c6-dbd91a410d3a.png)

**Comment by TobiasReich** [comment]
And the new version gives me several errors like

`"error: TypeError: Cannot read property 'value' of undefined"`

This did not happen in version 2.6.18

**Comment by TobiasReich** [comment]
Thanks!
