### ISSUE TITLE
Rotation not applied

### ISSUE THREAD

**Issue by TobiasReich** [Ashung/svg2vectordrawable#41]
There seems to be another issue.

The transformation of groups are not applied.

In the svg there is this tag:

`<g id="Group" transform="translate(17.066987, 16.883975) rotate(-30.000000) translate(-17.066987, -16.883975) translate(9.566987, 3.383975)" fill="#FFB74D">`

which works fine from IDE but is not applied in the framework.

[svgRotation.zip](https://github.com/Ashung/svg2vectordrawable/files/3669476/svgRotation.zip)

**Comment by Ashung** [comment]
Fixed, update version 2.6.20

**Comment by TobiasReich** [comment]
Is 2.6.20 already available for download? I can't get that one via npm install. Thanks!
