### ISSUE TITLE
Broken test "supports groups with multiple transforms"

### ISSUE THREAD

**Issue by guliash** [Ashung/svg2vectordrawable#45]
The test was broken twice:
1) ae471b17d43e855ec996310de7c4b38d84de37b9 when default black fill was removed.
2) 219d2d69c5814c2c589ca5d67d10440d1250dd6c when svgo config was updated.

I understand the first commit.
But why the second change is needed? Could not find any PR describing the change.

@Ashung could you please require tests for each PR? This library is pretty much easily testable so I think it is not much for a contributor to write test.

**Comment by Ashung** [comment]
The second change if for #39 and #40.

**Comment by guliash** [comment]
Thank you for reply. I see that you have already fixed the test. Thank you.
