### ISSUE TITLE
Cannot read property 'hasStyle' from undefined

### ISSUE THREAD

**Issue by Kwerag** [Ashung/svg2vectordrawable#50]
I have multiple images with inline `style="..."` elements e.g. 
```
<clipPath id="...">
		<use xlink:href="..." style="overflow:visible;"/>
</clipPath>
```
When running s2v I get 
`Error Cannot read property 'hasStyle' of undefined while converting file /.../mysvg.svg`

When I remove the `style="overflow:visible;` it works (but the image looks not as the original of course)

Do you know why that error occurs?

**Comment by alpox** [comment]
A short trackdown revealed that the origin of the error is likely located here:
https://github.com/svg/svgo/blob/master/lib/svgo/jsAPI.js#L291

When trying to [add the style attribute](https://github.com/Ashung/svg2vectordrawable/blob/master/lib/svg-to-vectordrawable.js#L100)

The value `this.style` in the dependency does not seem to be set - it may have to be initialized by adding a [CSSStyleDeclaration](https://github.com/svg/svgo/blob/master/lib/svgo/css-style-declaration.js) to the [JSAPI constructor](https://github.com/Ashung/svg2vectordrawable/blob/master/lib/svg-to-vectordrawable.js#L97)

**Comment by Kwerag** [comment]
And I found a second issue: 
Could it be, that clip-path in the <style> block is not supported?

`.st1{clip-path:url(#SVGID_2_);}`
