### ISSUE TITLE
Sometimes colors become black

### ISSUE THREAD

**Issue by sketchbookgames** [Ashung/svg2vectordrawable#8]
Might be related to previous issue with default color: https://github.com/Ashung/svg2vectordrawable/commit/eaf35145aff012f134e8fb27804f9760789ca52d

Fairly often I see converted assets that were not black in the input SVG become black in the output VectorDrawable.

Since it did not always occur I have provided a sample with and without the concern to help with the root cause.
It seems to only occur if more than one path is using the same style in the SVG.

**SAMPLE 1 exhibiting problem**
input exhibiting problem
`<?xml version="1.0" encoding="utf-8"?>

<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 48 48" style="enable-background:new 0 0 48 48;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#FFFFFF;}
</style>
	<path class="st0" d="M10,30H5L10,10h5v20z"/>
	<path class="st0" d="M20,40H5L20,30h5v0z"/>
</svg>
`
output exhibiting problem
`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportWidth="48"
    android:viewportHeight="48">
    <path
        android:fillColor="#000000"
        android:pathData="M10 30H5l5-20h5v20z"/>
    <path
        android:fillColor="#000000"
        android:pathData="M20 40H5l15-10h5z"/>
</vector>
`
expected 
`fillColor="#FFFFFF"`

**SAMPLE 2 not exhibiting problem**
similar input but not exhibiting problem (has 2 colors)
`<?xml version="1.0" encoding="utf-8"?>

<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 48 48" style="enable-background:new 0 0 48 48;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#FFFFFF;}
	.st1{fill:#FF0000;}
</style>
	<path class="st0" d="M10,30H5L10,10h5v20z"/>
	<path class="st1" d="M20,40H5L20,30h5v0z"/>
</svg>
`
output without problem
`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportWidth="48"
    android:viewportHeight="48">
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M10 30H5l5-20h5v20z"/>
    <path
        android:fillColor="#FF0000"
        android:pathData="M20 40H5l15-10h5z"/>
</vector>
`
**SAMPLE 3 not exhibiting problem**
similar input but not exhibiting problem (has 2 colors)
`<?xml version="1.0" encoding="utf-8"?>

<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 48 48" style="enable-background:new 0 0 48 48;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#FFFFFF;}
</style>
	<path class="st0" d="M10,30H5L10,10h5v20z"/>
</svg>
`
output without problem
`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportWidth="48"
    android:viewportHeight="48">
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M10 30H5l5-20h5v20z"/>
</vector>
`

**Comment by Ashung** [comment]
Thank you for report.
